#!/bin/bash

echo "Please input an ip adress"
read ipAdress
echo "Now the prefix"
read prefix

if [ $prefix -eq 24]
then
numHosts= 256
else
numHosts=$((2**(32 - prefix)))
fi

IFS='.' read -r -a ip_parts <<< "$ipAddress"
network="${ip_parts[0]}.${ip_parts[1]}.${ip_parts[2]}"
binaryNet1=$(echo "obase=2;${ip_parts[0]}" | bc)
binaryNet2=$(echo "obase=2;${ip_parts[1]}" | bc)
binaryNet3=$(echo "obase=2;${ip_parts[2]}" | bc)
binaryNetwork="$binaryNet1.$binaryNet2.$binaryNet3"

output_file="ip_addresses.txt"

host=1

while [ "$host" -lt "$((numHosts - 1))" ]; do
    binaryHost=$(echo "obase=2;$host" | bc)
    printf '%08d' "$binaryNetwork" "$binaryHost" >> "$output_file"
    host=$((host + 1))
done

